"""create sustainable solutions table

Revision ID: 0735ef605a49
Revises: 655d866fc6dd
Create Date: 2025-11-28 13:58:38.192881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0735ef605a49'
down_revision = '655d866fc6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sustainable_solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sustainabe_id', sa.Integer(), nullable=True),
    sa.Column('solution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], name=op.f('fk_sustainable_solutions_solution_id_solutions')),
    sa.ForeignKeyConstraint(['sustainabe_id'], ['sustainable_goals.id'], name=op.f('fk_sustainable_solutions_sustainabe_id_sustainable_goals')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sustainable_solutions')
    # ### end Alembic commands ###
