"""add sustainable goals table

Revision ID: 367e8b9fa321
Revises: ab8588b8da60
Create Date: 2025-11-27 19:50:02.814875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367e8b9fa321'
down_revision = 'ab8588b8da60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sustainable_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sustainable_goals')
    # ### end Alembic commands ###
