"""create home section table

Revision ID: 655d866fc6dd
Revises: 367e8b9fa321
Create Date: 2025-11-28 09:05:37.083501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655d866fc6dd'
down_revision = '367e8b9fa321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('img_1', sa.String(), nullable=True),
    sa.Column('img_2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('heading'),
    sa.UniqueConstraint('text')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_sections')
    # ### end Alembic commands ###
