"""add accessor column to HomeSection table

Revision ID: aae09a02ee19
Revises: e8c463f91cab
Create Date: 2025-11-28 16:03:06.737110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae09a02ee19'
down_revision = 'e8c463f91cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accessor', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_sections', schema=None) as batch_op:
        batch_op.drop_column('accessor')

    # ### end Alembic commands ###
