"""add products model

Revision ID: cb984dca190d
Revises: 2ec26f579abc
Create Date: 2025-11-27 15:55:12.676332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb984dca190d'
down_revision = '2ec26f579abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('no_made', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], name=op.f('fk_products_model_solution_id_solutions')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_model')
    # ### end Alembic commands ###
