"""update sustainable solutions table

Revision ID: e8c463f91cab
Revises: 0735ef605a49
Create Date: 2025-11-28 14:23:10.414859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c463f91cab'
down_revision = '0735ef605a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sustainable_solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sustainable_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_sustainable_solutions_sustainabe_id_sustainable_goals', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sustainable_solutions_sustainable_id_sustainable_goals'), 'sustainable_goals', ['sustainable_id'], ['id'])
        batch_op.drop_column('sustainabe_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sustainable_solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sustainabe_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_sustainable_solutions_sustainable_id_sustainable_goals'), type_='foreignkey')
        batch_op.create_foreign_key('fk_sustainable_solutions_sustainabe_id_sustainable_goals', 'sustainable_goals', ['sustainabe_id'], ['id'])
        batch_op.drop_column('sustainable_id')

    # ### end Alembic commands ###
